import random
kelimeler = ["gözəl ","bilmək ","sual","sağalmaq ","getmək","zaman","su","yarmaq","dəli","görmək",
             "yenidən", "çox", "fakt", "pul", "oynamaq", "çiçək", "şəhər", "yüksəlmək", "döyüş", "varlıq", "etmək",
             "güvən", "lazım", "müalicə", "bir", "rahat", "soyuq", "orası", "kitab", "paylaşmaq", "hesap", "bədən",
             "torpaq", "üzəri", "sistem", "xoş", "çəkilmək", "texnik", "yaxınlaşmaq", "il", "tarix", "kəsir", "bacı",
             "incə", "deyər", "oyda", "qarşılıql","vermək", "sahib", "artıq", "kişi", "diyar", "dönəm", "yenə", "bunlar",
             "kitab", "xəta", "tapmaq", "siz", "dövlət", "qabaq", "enerji", "baxmaq", "xiyar", "oyun", "baş", "başlamaq",
             "tutmaq", "birbiri", "heçbir", "yatmaq", "su", "ürək", "hal", "doğru", "orta", "başqa", "böyük", "etmək",
             "yeni", "çoxlu", "soruşmaq", "onlar", "açmaq", "hem", "həb", "səs", "ağlamaq", "dəli", "saat", "hasil",
             'bir', 'veteran', 'olmak', 'bu', 'içki', 'onuncu', 'ben', 'demək', 'çox', 'yaşıl', 'ana', 'kimi', 'daha', 'almaq',
             'var', 'özün', 'gəlmək', 'ilə', 'vermək', 'baba', 'sonra', 'qədir', 'yer', 'ata', 'insan', 'deyil', 'hər',
             'istəmək', 'ilan', 'çıkmak', 'görmək', 'gün', 'biz', 'getmkə', 'iş', 'şey', 'axtarmaq', 'iki', 'bilmək', 'əl', 'zaman',
             'ya', 'çocuk', 'iki', 'baxmakq', 'çalışmak', 'içində', 'böyük', 'yox', 'başlamaq', 'yol', 'düzgün', 'feil', 'siz',
             'söz', 'yaradmaq', 'yaxşı', 'qadın', 'evli', 'demək', 'bulunmak', 'söylemek', 'göz', 'gerekmek', 'dünya',
             'baş', 'vaxt', 'yan', 'getmək', 'sən', 'onlar', 'yeni', 'öncə', 'başqa', 'hal', 'orta', 'su', 'girmek', 'ülke',
             'yemək', 'heçnə', 'oxumaq', 'necə', 'bütün', 'qarşı', 'tapmaq', 'evvli', 'yaşamak', 'düşünmek', 'aynı', 'iç', 'ancaq',
             'kişi', 'bunlar', 'veya', 'ilk', 'göre', 'qabaq', 'son', 'biri', 'şəkil', 'önemli', 'yüz', 'həmin', 'göstərmək', 'etmək',
             'alt', 'gətirmək', 'işlətmək', 'çünkü', 'tərəf', 'kimdi', 'adam', 'onun', 'diğer', 'artık', 'ütüntə', 'səs', 'hep',
             'doğru', 'dayanmaq', 'qız', 'tüm', 'çekmek', 'konuşmak', 'pullu', 'anlamak', 'anne', 'az', 'bazar', 'baba', 'hayat',
             'sadece', 'balaca', 'çox', 'bilgi', 'an', 'soruşma', 'bunun', 'öyle', 'yine', 'sağalmaq', 'sonuç', 'kullanılmak', 'dış',
             'ad', 'yəni', 'vaxt', 'dönmek', 'açmak', 'oturmak', 'anlatmak', 'bırakmak', 'həmən', 'saat', 'yaş', 'sorun', 'devlet',
             'sahib', 'sıra', 'yazmak', 'yüzdə', 'ay', 'atmak', 'tutmaq', 'burun', 'qəza', 'yarı', 'duymak', 'söz', 'güzel',
             'sevmek', 'biraz', 'zor', 'çıkarmak', 'suni', 'koymak', 'tək', 'sistem', 'birlikte', 'verilmek', 'kim', 'alınmak', 'genç',
             'kapı', 'kitab', 'üzerine', 'burada', 'gecə', 'alan', 'bərbər', 'işte', 'beklemek', 'uzun', 'hiçbir', 'bugün', 'dönem',
             'dost', 'soyad', 'aile', 'üç', 'okumaq','kişi', 'hərkəs', 'güc', 'bəlmək', 'doğru', 'tam', 'gecə', 'Riyad',
             'çevrə', 'köhnə', 'zəng', 'yaşma', 'əhali', 'yaxın', 'yol', 'bəy', 'tarix', 'özellik', 'bölüm', 'şəxsi', 'ağıl',
             'kimsə', 'pak', 'baş', 'gerek', 'yaxın', 'anlamaq', 'yuxarı', 'banka', 'kez', 'ayak', 'daşımaq', 'geri', 'toplu',
             'maşın', 'maddə', 'türk', 'qəlyan', 'görüldü', 'hava', 'sayı', 'farklı', 'grup', 'otaq', 'bacı', 'dolmaq', 'xəbər',
             'allah', 'ayrıca', 'gələn', 'çin', 'sual', 'arxa', 'qazanmaq', 'yazı', 'dərs', 'açıq', 'öyrənmək', 'sürmək',
             'dil', 'şirket', 'kaynak', 'bitmək', 'program', 'devametmek', 'hareket', 'rəng', 'açılmaq', 'hak', 'inanmaq',
             'çalmaq', 'acı', 'parça', 'qazet', 'yaratmaq', 'yaxşı', 'dəyər', 'tanımaq', 'yapı', 'doktor', 'gəlir',
             'hərbiçi', 'amaç', 'bölge', 'kino', 'üzere', 'müşteri', 'zaten', 'telefon', 'eğitim', 'deniz', 'ikinci',
             'qalxmaq', 'hatta', 'qar', 'gəlir', 'keçən', 'bel', 'düşünce', 'milyon', 'oynamak', 'dəyişmək', 'tütün',
             'yaratmaq', 'xal', 'fikir', 'keçmək', 'söyüş', 'kurmak', 'fakat', 'buna', 'resim', 'ışıq', 'içmək',
             'xanım', 'xəstə', 'ehtiyac', 'nöktə', 'yönlü', 'xəta', 'oyun', 'artmak', 'yeniden', 'işlem', 'kısa', 'kolay',
             'hal', 'qan', 'aslında', 'ağıl', 'orada', 'diqqət', 'uzaq', 'bilgisayar', 'gələcək', 'görünmek',
             'şəkil', 'oğul', 'dinlemek', 'uyğun', 'manat', 'passiv', 'dakika', 'unutmak', 'yürümek', 'böylece', 'kötü',
             'maşın', 'ağız', 'duygu', 'uygulamak', 'xala', 'örnek', 'birçok', 'izlemek', 'derece', 'mümkün', 'şöyle',
             'duvar', 'on', 'sənə', 'ana', 'xəstəlik', 'öğrenci', 'televizyon', 'yöntem', 'masa', 'ölmek', 'takım', 'üst',
             'baş', 'müzik', 'ayrılmak', 'enerji', 'üniversite', 'spor', 'türlü', 'can', 'rağmen', 'kısım', 'ölüm',
             'süretli', 'sağlıq', 'çeşid', 'banan', 'hissetmek', 'oysa', 'sabah', 'internet', 'teknik', 'dışarı',
             'mərkəz', 'orta', 'yerinə', 'düz', 'kənd', 'yorulmaq', 'aşağı', 'cevap', 'yatmak', 'toprak', '', 'akşam',
             'sarı', 'götürmek', 'qatılmaq', 'yoksa', 'qurmaq', 'ödemek', 'sanki', 'kan', 'hasta', 'şehir', 'inmek',
             'qara', 'bilinmek', 'həftə', 'lənpə', 'hesab', 'otomobil', 'yabancı', 'davranış', 'mutfak', 'kent', 'bazen',
             'vacib', 'ayrı', 'qiymət', 'hakkında', 'qaldırmaq', 'kol', 'tək', 'hazırlamaq', 'cam', 'sonunda', 'yavaş',
             'lazım', 'dəyər', 'arvad', 'yanlış', 'varlı', 'tar', 'arı', 'təkcə', 'satış', 'içeri', 'doğal', 'sahipolmak',
             'ekonom', 'acı', 'xeyir', 'qorumaq', 'qat', 'ekonomi', 'genel', 'bildirmək', 'fotoğraf', 'hayvan', 'savaş',
             'yumurta', 'aşırı', 'plan', 'istəmək', 'kərim', 'kriz', 'birlik',
             'qapanmaq'
             ]


def kelime_sec():
    return random.choice(kelimeler)
